name: CI Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 360 # 6 hours timeout

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js version 16.x
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Clean previous Cypress results
      - name: Clean Cypress results
        run: rm -rf ${{ github.workspace }}/cypress/results

      # Step 5: Run Cypress tests
      - name: Run Cypress tests
        run: npm run cypress:run
        continue-on-error: true

      # Step 6: Publish Cucumber report (if exists)
      - name: Publish Cucumber Report
        run: |
          if [ -d "${{ github.workspace }}/cypress/generated" ]; then
            echo "Publishing Cucumber report..."
            # Add the command to publish the cucumber report if needed
          fi

      # Step 7: Check for Cypress screenshots and upload as artifact if exists
      - name: Check and upload Cypress screenshots
        run: |
          if [ -d "${{ github.workspace }}/cypress/screenshots" ]; then
            echo "Screenshots exist, uploading..."
            echo "SCREENSHOTSEXIST=true" >> $GITHUB_ENV
          fi

      # Step 8: Upload screenshots as an artifact
      - name: Upload screenshots as artifacts
        if: env.SCREENSHOTSEXIST == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: ${{ github.workspace }}/cypress/screenshots

      # Step 9: Check for Cypress videos and upload as artifact if exists
      - name: Check and upload Cypress videos
        run: |
          if [ -d "${{ github.workspace }}/cypress/videos" ]; then
            echo "Videos exist, uploading..."
            echo "VIDEOSEXIST=true" >> $GITHUB_ENV
          fi

      # Step 10: Upload videos as an artifact
      - name: Upload videos as artifacts
        if: env.VIDEOSEXIST == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: videos
          path: ${{ github.workspace }}/cypress/videos

      # Step 11: Publish test results in JUnit format
      - name: Publish test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ${{ github.workspace }}/cypress/results/**/*.xml